/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Main;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import net.sf.jasperreports.engine.JREmptyDataSource;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.data.JRBeanCollectionDataSource;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Zhafron
 */
public class InputDataDiri extends javax.swing.JFrame {

    /**
     * Creates new form Input
     */
    public InputDataDiri() {
        initComponents();
        pa.addItem("PUTU BAGUS ADIDYANA A.P., ST., M.Kom.");
        pa.addItem("NOVA NOOR KAMALA SARI, ST., M.Kom.");
        //Matkul1
        cmbmatkul1.addItem("-");
        cmbmatkul1.addItem("PENDIDIKAN AGAMA ISLAM");
        cmbmatkul1.addItem("BAHASA INGGRIS II");
        cmbmatkul1.addItem("ALGORITMA & PEMROGRAMAN II");
        cmbmatkul1.addItem("STRUKTUR DATA");
        cmbmatkul1.addItem("MATEMATIKA DISKIT");
        cmbmatkul1.addItem("SISTEM OPERASI");
        cmbmatkul1.addItem("PENGANTAR ARSITEKTUR KOMPUTER");
        cmbmatkul1.addItem("KALKULUS II");
        //Matkul2
        cmbmatkul2.addItem("-");
        cmbmatkul2.addItem("PENDIDIKAN AGAMA ISLAM");
        cmbmatkul2.addItem("BAHASA INGGRIS II");
        cmbmatkul2.addItem("ALGORITMA & PEMROGRAMAN II");
        cmbmatkul2.addItem("STRUKTUR DATA");
        cmbmatkul2.addItem("MATEMATIKA DISKIT");
        cmbmatkul2.addItem("SISTEM OPERASI");
        cmbmatkul2.addItem("PENGANTAR ARSITEKTUR KOMPUTER");
        cmbmatkul2.addItem("KALKULUS II");
        //Matkul3
        cmbmatkul3.addItem("-");
        cmbmatkul3.addItem("PENDIDIKAN AGAMA ISLAM");
        cmbmatkul3.addItem("BAHASA INGGRIS II");
        cmbmatkul3.addItem("ALGORITMA & PEMROGRAMAN II");
        cmbmatkul3.addItem("STRUKTUR DATA");
        cmbmatkul3.addItem("MATEMATIKA DISKIT");
        cmbmatkul3.addItem("SISTEM OPERASI");
        cmbmatkul3.addItem("PENGANTAR ARSITEKTUR KOMPUTER");
        cmbmatkul3.addItem("KALKULUS II");
        //Matkul4
        cmbmatkul4.addItem("-");
        cmbmatkul4.addItem("PENDIDIKAN AGAMA ISLAM");
        cmbmatkul4.addItem("BAHASA INGGRIS II");
        cmbmatkul4.addItem("ALGORITMA & PEMROGRAMAN II");
        cmbmatkul4.addItem("STRUKTUR DATA");
        cmbmatkul4.addItem("MATEMATIKA DISKIT");
        cmbmatkul4.addItem("SISTEM OPERASI");
        cmbmatkul4.addItem("PENGANTAR ARSITEKTUR KOMPUTER");
        cmbmatkul4.addItem("KALKULUS II");
        //Matkul5
        cmbmatkul5.addItem("-");
        cmbmatkul5.addItem("PENDIDIKAN AGAMA ISLAM");
        cmbmatkul5.addItem("BAHASA INGGRIS II");
        cmbmatkul5.addItem("ALGORITMA & PEMROGRAMAN II");
        cmbmatkul5.addItem("STRUKTUR DATA");
        cmbmatkul5.addItem("MATEMATIKA DISKIT");
        cmbmatkul5.addItem("SISTEM OPERASI");
        cmbmatkul5.addItem("PENGANTAR ARSITEKTUR KOMPUTER");
        cmbmatkul5.addItem("KALKULUS II");
        //Matkul6
        cmbmatkul6.addItem("-");
        cmbmatkul6.addItem("PENDIDIKAN AGAMA ISLAM");
        cmbmatkul6.addItem("BAHASA INGGRIS II");
        cmbmatkul6.addItem("ALGORITMA & PEMROGRAMAN II");
        cmbmatkul6.addItem("STRUKTUR DATA");
        cmbmatkul6.addItem("MATEMATIKA DISKIT");
        cmbmatkul6.addItem("SISTEM OPERASI");
        cmbmatkul6.addItem("PENGANTAR ARSITEKTUR KOMPUTER");
        cmbmatkul6.addItem("KALKULUS II");
        //Matkul7
        cmbmatkul7.addItem("-");
        cmbmatkul7.addItem("PENDIDIKAN AGAMA ISLAM");
        cmbmatkul7.addItem("BAHASA INGGRIS II");
        cmbmatkul7.addItem("ALGORITMA & PEMROGRAMAN II");
        cmbmatkul7.addItem("STRUKTUR DATA");
        cmbmatkul7.addItem("MATEMATIKA DISKIT");
        cmbmatkul7.addItem("SISTEM OPERASI");
        cmbmatkul7.addItem("PENGANTAR ARSITEKTUR KOMPUTER");
        cmbmatkul7.addItem("KALKULUS II");
        //Matkul8
        cmbmatkul8.addItem("-");
        cmbmatkul8.addItem("PENDIDIKAN AGAMA ISLAM");
        cmbmatkul8.addItem("BAHASA INGGRIS II");
        cmbmatkul8.addItem("ALGORITMA & PEMROGRAMAN II");
        cmbmatkul8.addItem("STRUKTUR DATA");
        cmbmatkul8.addItem("MATEMATIKA DISKIT");
        cmbmatkul8.addItem("SISTEM OPERASI");
        cmbmatkul8.addItem("PENGANTAR ARSITEKTUR KOMPUTER");
        cmbmatkul8.addItem("KALKULUS II");

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        innama = new javax.swing.JTextField();
        innim = new javax.swing.JTextField();
        insemester = new javax.swing.JTextField();
        pa = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        cmbmatkul1 = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        nilai1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cmbmatkul2 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        nilai2 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        cmbmatkul3 = new javax.swing.JComboBox();
        jLabel10 = new javax.swing.JLabel();
        nilai3 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        cmbmatkul4 = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        nilai4 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        cmbmatkul5 = new javax.swing.JComboBox();
        jLabel14 = new javax.swing.JLabel();
        nilai5 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        cmbmatkul6 = new javax.swing.JComboBox();
        nilai6 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        cmbmatkul7 = new javax.swing.JComboBox();
        nilai7 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        cmbmatkul8 = new javax.swing.JComboBox();
        nilai8 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        inipsemlalu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(800, 500));

        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });

        jLabel1.setText("Nama :");

        jLabel2.setText("NIM :");

        jLabel3.setText("Semester :");

        jLabel4.setText("Pembimbing Akademik :");

        pa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paActionPerformed(evt);
            }
        });

        jLabel5.setText("Mata Kuliah :");

        cmbmatkul1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmatkul1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Nilai :");

        jLabel7.setText("Mata Kuliah :");

        cmbmatkul2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmatkul2ActionPerformed(evt);
            }
        });

        jLabel8.setText("Nilai :");

        jLabel9.setText("Mata Kuliah :");

        cmbmatkul3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmatkul3ActionPerformed(evt);
            }
        });

        jLabel10.setText("Nilai :");

        jLabel11.setText("Mata Kuliah :");

        cmbmatkul4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmatkul4ActionPerformed(evt);
            }
        });

        jLabel12.setText("Nilai :");

        jLabel13.setText("Mata Kuliah :");

        cmbmatkul5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmatkul5ActionPerformed(evt);
            }
        });

        jLabel14.setText("Nilai :");

        jLabel15.setText("Mata Kuliah :");

        cmbmatkul6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmatkul6ActionPerformed(evt);
            }
        });

        jLabel16.setText("Nilai :");

        jLabel17.setText("Mata Kuliah :");

        cmbmatkul7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmatkul7ActionPerformed(evt);
            }
        });

        jLabel18.setText("Nilai :");

        jLabel19.setText("Mata Kuliah :");

        cmbmatkul8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbmatkul8ActionPerformed(evt);
            }
        });

        jLabel20.setText("Nilai :");

        jLabel21.setText("IP Semester Lalu :");

        inipsemlalu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inipsemlaluActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(submit))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pa, 0, 112, Short.MAX_VALUE)
                            .addComponent(insemester, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(innim, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(innama, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(inipsemlalu, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbmatkul2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nilai2, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbmatkul3, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nilai3, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addComponent(jLabel21))
                .addGap(37, 37, 37))
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbmatkul5, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nilai5, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20))
                        .addGap(35, 35, 35)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cmbmatkul8, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nilai8, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbmatkul4, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nilai4, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbmatkul1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nilai1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(nilai6)
                                    .addComponent(cmbmatkul6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel18))
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cmbmatkul7, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(nilai7, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(innama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(innim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(cmbmatkul2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(nilai2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(insemester, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(pa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(cmbmatkul3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(nilai3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(inipsemlalu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(cmbmatkul1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(nilai1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(cmbmatkul6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(nilai6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(cmbmatkul4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(nilai4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(cmbmatkul7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18)
                            .addComponent(nilai7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(cmbmatkul5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(nilai5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(cmbmatkul8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(nilai8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submit)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        String padosen = (String) pa.getSelectedItem();
        String matkul1 = (String) cmbmatkul1.getSelectedItem();
        String matkul2 = (String) cmbmatkul2.getSelectedItem();
        String matkul3 = (String) cmbmatkul3.getSelectedItem();
        String matkul4 = (String) cmbmatkul4.getSelectedItem();
        String matkul5 = (String) cmbmatkul5.getSelectedItem();
        String matkul6 = (String) cmbmatkul6.getSelectedItem();
        String matkul7 = (String) cmbmatkul7.getSelectedItem();
        String matkul8 = (String) cmbmatkul8.getSelectedItem();
        float n1 = ParseFloat(nilai1.getText());
        float n2 = ParseFloat(nilai2.getText());
        float n3 = ParseFloat(nilai3.getText());
        float n4 = ParseFloat(nilai4.getText());
        float n5 = ParseFloat(nilai5.getText());
        float n6 = ParseFloat(nilai6.getText());
        float n7 = ParseFloat(nilai7.getText());
        float n8 = ParseFloat(nilai8.getText());
        float semlalu = ParseFloat(inipsemlalu.getText());
        float bebpai = 0;
        float bebbing = 0;
        float bebap = 0;
        float bebsd = 0;
        float bebmd = 0;
        float bebso = 0;
        float bebpak = 0;
        float bebkal = 0;
        float lulbebpai = 0;
        float lulbebbing = 0;
        float lulbebap = 0;
        float lulbebsd = 0;
        float lulbebmd = 0;
        float lulbebso = 0;
        float lulbebpak = 0;
        float lulbebkal = 0;
        float totallulus = 0;
        float totalbeb = 0;
        float HKn1 = 0;
        float HKn2 = 0;
        float HKn3 = 0;
        float HKn4 = 0;
        float HKn5 = 0;
        float HKn6 = 0;
        float HKn7 = 0;
        float HKn8 = 0;
        float totmutusem = 0;
        float ipsemtot = 0;
        float mutusemlalu = 0;
        float mutukumul = 0;
        float ipkumul = 0;
        float bebankumul = 0;
        float luluskumul = 0;
        float sksyad = 24;
        String nama = innama.getText();
        String nim = innim.getText();
        String semester = insemester.getText();
        Map params = new HashMap();

        List<Data> listOfDummyData = new ArrayList<Data>();
        Data data = new Data();

        //Nilai 1
        if (n1 == 4.00) {
            data.setHm1("A");
        } else if (n1 == 3.50) {
            data.setHm1("B+");
        } else if (n1 == 3.00) {
            data.setHm1("B");
        } else if (n1 == 2.50) {
            data.setHm1("C+");
        } else if (n1 == 2.00) {
            data.setHm1("C");
        } else if (n1 == 1.50) {
            data.setHm1("D+");
        } else if (n1 == 1.00) {
            data.setHm1("D");
        } else if (n1 < 1.00) {
            data.setHm1("E");
        }
        if (n1 >= 2.00 && n1 <= 4.00) {
            data.setKet1("L");
        } else if (n1 < 2.00) {
            data.setKet1("TL");
        }
        //Nilai 2
        if (n2 == 4.00) {
            data.setHm2("A");
        } else if (n2 == 3.50) {
            data.setHm2("B+");
        } else if (n2 == 3.00) {
            data.setHm2("B");
        } else if (n2 == 2.50) {
            data.setHm2("C+");
        } else if (n2 == 2.00) {
            data.setHm2("C");
        } else if (n2 == 1.50) {
            data.setHm2("D+");
        } else if (n2 == 1.00) {
            data.setHm2("D");
        } else if (n2 < 1.00) {
            data.setHm2("E");
        }
        if (n2 >= 2.00 && n2 <= 4.00) {
            data.setKet2("L");
        } else if (n2 < 2.00) {
            data.setKet2("TL");
        }
        //Nilai 3
        if (n3 == 4.00) {
            data.setHm3("A");
        } else if (n3 == 3.50) {
            data.setHm3("B+");
        } else if (n3 == 3.00) {
            data.setHm3("B");
        } else if (n3 == 2.50) {
            data.setHm3("C+");
        } else if (n3 == 2.00) {
            data.setHm3("C");
        } else if (n3 == 1.50) {
            data.setHm3("D+");
        } else if (n3 == 1.00) {
            data.setHm3("D");
        } else if (n3 < 1.00) {
            data.setHm3("E");
        }
        if (n3 >= 2.00 && n3 <= 4.00) {
            data.setKet3("L");
        } else if (n3 < 2.00) {
            data.setKet3("TL");
        }
        //Nilai 4
        if (n4 == 4.00) {
            data.setHm4("A");
        } else if (n4 == 3.50) {
            data.setHm4("B+");
        } else if (n4 == 3.00) {
            data.setHm4("B");
        } else if (n4 == 2.50) {
            data.setHm4("C+");
        } else if (n4 == 2.00) {
            data.setHm4("C");
        } else if (n4 == 1.50) {
            data.setHm4("D+");
        } else if (n4 == 1.00) {
            data.setHm4("D");
        } else if (n4 < 1.00) {
            data.setHm4("E");
        }
        if (n4 >= 2.00 && n4 <= 4.00) {
            data.setKet4("L");
        } else if (n4 < 2.00) {
            data.setKet4("TL");
        }
        //Nilai 5
        if (n5 == 4.00) {
            data.setHm5("A");
        } else if (n5 == 3.50) {
            data.setHm5("B+");
        } else if (n5 == 3.00) {
            data.setHm5("B");
        } else if (n5 == 2.50) {
            data.setHm5("C+");
        } else if (n5 == 2.00) {
            data.setHm5("C");
        } else if (n5 == 1.50) {
            data.setHm5("D+");
        } else if (n5 == 1.00) {
            data.setHm5("D");
        } else if (n5 < 1.00) {
            data.setHm5("E");
        }
        if (n5 >= 2.00 && n5 <= 4.00) {
            data.setKet5("L");
        } else if (n5 < 2.00) {
            data.setKet5("TL");
        }
        //Nilai 6
        if (n6 == 4.00) {
            data.setHm6("A");
        } else if (n6 == 3.50) {
            data.setHm6("B+");
        } else if (n6 == 3.00) {
            data.setHm6("B");
        } else if (n6 == 2.50) {
            data.setHm6("C+");
        } else if (n6 == 2.00) {
            data.setHm6("C");
        } else if (n6 == 1.50) {
            data.setHm6("D+");
        } else if (n6 == 1.00) {
            data.setHm6("D");
        } else if (n6 < 1.00) {
            data.setHm6("E");
        }
        if (n6 >= 2.00 && n6 <= 4.00) {
            data.setKet6("L");
        } else if (n6 < 2.00) {
            data.setKet6("TL");
        }
        //Nilai 7
        if (n7 == 4.00) {
            data.setHm7("A");
        } else if (n7 == 3.50) {
            data.setHm7("B+");
        } else if (n7 == 3.00) {
            data.setHm7("B");
        } else if (n7 == 2.50) {
            data.setHm7("C+");
        } else if (n7 == 2.00) {
            data.setHm7("C");
        } else if (n7 == 1.50) {
            data.setHm7("D+");
        } else if (n7 == 1.00) {
            data.setHm7("D");
        } else if (n7 < 1.00) {
            data.setHm7("E");
        }
        if (n7 >= 2.00 && n7 <= 4.00) {
            data.setKet7("L");
        } else if (n7 < 2.00) {
            data.setKet7("TL");
        }
        //Nilai 8
        if (n8 == 4.00) {
            data.setHm8("A");
        } else if (n8 == 3.50) {
            data.setHm8("B+");
        } else if (n8 == 3.00) {
            data.setHm8("B");
        } else if (n8 == 2.50) {
            data.setHm8("C+");
        } else if (n8 == 2.00) {
            data.setHm8("C");
        } else if (n8 == 1.50) {
            data.setHm8("D+");
        } else if (n8 == 1.00) {
            data.setHm8("D");
        } else if (n8 < 1.00) {
            data.setHm8("E");
        }
        if (n8 >= 2.00 && n8 <= 4.00) {
            data.setKet8("L");
        } else if (n8 < 2.00) {
            data.setKet8("TL");
        }

        //Matkul 1
        data.setMatkul1(matkul1);
        if ("PENDIDIKAN AGAMA ISLAM".equals(matkul1)) {
            bebpai = (float) 3.00;
            data.setSandi1("DBPK1011");
            data.setSks1(3);
            data.setNm1(n1);
            HKn1 = n1 * 3;
            data.setKn1(HKn1);
            if (n1 >= 2.00) {
                lulbebpai = (float) 3.00;
            }
        } else if ("BAHASA INGGRIS II".equals(matkul1)) {
            bebbing = (float) 2.00;
            data.setSandi1("DBPK1092");
            data.setSks1(2);
            data.setNm1(n1);
            HKn1 = n1 * 2;
            data.setKn1(HKn1);
            if (n1 >= 2.00) {
                lulbebbing = (float) 2.00;
            }
        } else if ("ALGORITMA & PEMROGRAMAN II".equals(matkul1)) {
            bebap = (float) 3.00;
            data.setSandi1("DBKK1102");
            data.setSks1(3);
            data.setNm1(n1);
            HKn1 = n1 * 3;
            data.setKn1(HKn1);
            if (n1 >= 2.00) {
                lulbebap = (float) 3.00;
            }
        } else if ("STRUKTUR DATA".equals(matkul1)) {
            bebsd = (float) 3.00;
            data.setSandi1("DBKK1172");
            data.setSks1(3);
            data.setNm1(n1);
            HKn1 = n1 * 3;
            data.setKn1(HKn1);
            if (n1 >= 2.00) {
                lulbebsd = (float) 3.00;
            }
        } else if ("MATEMATIKA DISKIT".equals(matkul1)) {
            bebmd = (float) 3.00;
            data.setSandi1("DBKK1191");
            data.setSks1(3);
            data.setNm1(n1);
            HKn1 = n1 * 3;
            data.setKn1(HKn1);
            if (n1 >= 2.00) {
                lulbebmd = (float) 3.00;
            }
        } else if ("SISTEM OPERASI".equals(matkul1)) {
            bebso = (float) 3.00;
            data.setSandi1("DBKB1042");
            data.setSks1(3);
            data.setNm1(n1);
            HKn1 = n1 * 3;
            data.setKn1(HKn1);
            if (n1 >= 2.00) {
                lulbebso = (float) 3.00;
            }
        } else if ("PENGANTAR ARSITEKTUR KOMPUTER".equals(matkul1)) {
            bebpak = (float) 3.00;
            data.setSandi1("DBKK1272");
            data.setSks1(3);
            data.setNm1(n1);
            HKn1 = n1 * 3;
            data.setKn1(HKn1);
            if (n1 >= 2.00) {
                lulbebpak = (float) 3.00;
            }
        } else if ("KALKULUS II".equals(matkul1)) {
            bebkal = (float) 2.00;
            data.setSandi1("DBKK1062");
            data.setSks1(2);
            data.setNm1(n1);
            HKn1 = n1 * 2;
            data.setKn1(HKn1);
            if (n1 >= 2.00) {
                lulbebkal = (float) 2.00;
            }
        }
        //Matkul 2
        data.setMatkul2(matkul2);
        if ("PENDIDIKAN AGAMA ISLAM".equals(matkul2)) {
            bebpai = (float) 3.00;
            data.setSandi2("DBPK1011");
            data.setSks2(3);
            data.setNm2(n2);
            HKn2 = n2 * 3;
            data.setKn2(HKn2);
            if (n2 >= 2.00) {
                lulbebpai = (float) 3.00;
            }
        } else if ("BAHASA INGGRIS II".equals(matkul2)) {
            bebbing = (float) 2.00;
            data.setSandi2("DBPK1092");
            data.setSks2(2);
            data.setNm2(n2);
            HKn2 = n2 * 2;
            data.setKn2(HKn2);
            if (n2 >= 2.00) {
                lulbebbing = (float) 2.00;
            }
        } else if ("ALGORITMA & PEMROGRAMAN II".equals(matkul2)) {
            bebap = (float) 3.00;
            data.setSandi2("DBKK1102");
            data.setSks2(3);
            data.setNm2(n2);
            HKn2 = n2 * 3;
            data.setKn2(HKn2);
            if (n2 >= 2.00) {
                lulbebap = (float) 3.00;
            }
        } else if ("STRUKTUR DATA".equals(matkul2)) {
            bebsd = (float) 3.00;
            data.setSandi2("DBKK1172");
            data.setSks2(3);
            data.setNm2(n2);
            HKn2 = n2 * 3;
            data.setKn2(HKn2);
            if (n2 >= 2.00) {
                lulbebsd = (float) 3.00;
            }
        } else if ("MATEMATIKA DISKIT".equals(matkul2)) {
            bebmd = (float) 3.00;
            data.setSandi2("DBKK1191");
            data.setSks2(3);
            data.setNm2(n2);
            HKn2 = n2 * 3;
            data.setKn2(HKn2);
            if (n2 >= 2.00) {
                lulbebmd = (float) 3.00;
            }
        } else if ("SISTEM OPERASI".equals(matkul2)) {
            bebso = (float) 3.00;
            data.setSandi2("DBKB1042");
            data.setSks2(3);
            data.setNm2(n2);
            HKn2 = n2 * 3;
            data.setKn2(HKn2);
            if (n2 >= 2.00) {
                lulbebso = (float) 3.00;
            }
        } else if ("PENGANTAR ARSITEKTUR KOMPUTER".equals(matkul2)) {
            bebpak = (float) 3.00;
            data.setSandi2("DBKK1272");
            data.setSks2(3);
            data.setNm2(n2);
            HKn2 = n2 * 3;
            data.setKn2(HKn2);
            if (n2 >= 2.00) {
                lulbebpak = (float) 3.00;
            }
        } else if ("KALKULUS II".equals(matkul2)) {
            bebkal = (float) 2.00;
            data.setSandi2("DBKK1062");
            data.setSks2(2);
            data.setNm2(n2);
            HKn2 = n2 * 2;
            data.setKn2(HKn2);
            if (n2 >= 2.00) {
                lulbebkal = (float) 2.00;
            }
        }
        //Matkul 3
        data.setMatkul3(matkul3);
        if ("PENDIDIKAN AGAMA ISLAM".equals(matkul3)) {
            bebpai = (float) 3.00;
            data.setSandi3("DBPK1011");
            data.setSks3(3);
            data.setNm3(n3);
            HKn3 = n3 * 3;
            data.setKn3(HKn3);
            if (n3 >= 2.00) {
                lulbebpai = (float) 3.00;
            }
        } else if ("BAHASA INGGRIS II".equals(matkul3)) {
            bebbing = (float) 2.00;
            data.setSandi3("DBPK1092");
            data.setSks3(2);
            data.setNm3(n3);
            HKn3 = n3 * 2;
            data.setKn3(HKn3);
            if (n3 >= 2.00) {
                lulbebbing = (float) 2.00;
            }
        } else if ("ALGORITMA & PEMROGRAMAN II".equals(matkul3)) {
            bebap = (float) 3.00;
            data.setSandi3("DBKK1102");
            data.setSks3(3);
            data.setNm3(n3);
            HKn3 = n3 * 3;
            data.setKn3(HKn3);
            if (n3 >= 2.00) {
                lulbebap = (float) 3.00;
            }
        } else if ("STRUKTUR DATA".equals(matkul3)) {
            bebsd = (float) 3.00;
            data.setSandi3("DBKK1172");
            data.setSks3(3);
            data.setNm3(n3);
            HKn3 = n3 * 3;
            data.setKn3(HKn3);
            if (n3 >= 2.00) {
                lulbebsd = (float) 3.00;
            }
        } else if ("MATEMATIKA DISKIT".equals(matkul3)) {
            bebmd = (float) 3.00;
            data.setSandi3("DBKK1191");
            data.setSks3(3);
            data.setNm3(n3);
            HKn3 = n3 * 3;
            data.setKn3(HKn3);
            if (n3 >= 2.00) {
                lulbebmd = (float) 3.00;
            }
        } else if ("SISTEM OPERASI".equals(matkul3)) {
            bebso = (float) 3.00;
            data.setSandi3("DBKB1042");
            data.setSks3(3);
            data.setNm3(n3);
            HKn3 = n3 * 3;
            data.setKn3(HKn3);
            if (n3 >= 2.00) {
                lulbebso = (float) 3.00;
            }
        } else if ("PENGANTAR ARSITEKTUR KOMPUTER".equals(matkul3)) {
            bebpak = (float) 3.00;
            data.setSandi3("DBKK1272");
            data.setSks3(3);
            data.setNm3(n3);
            HKn3 = n3 * 3;
            data.setKn3(HKn3);
            if (n3 >= 2.00) {
                lulbebpak = (float) 3.00;
            }
        } else if ("KALKULUS II".equals(matkul3)) {
            bebkal = (float) 2.00;
            data.setSandi3("DBKK1062");
            data.setSks3(2);
            data.setNm3(n3);
            HKn3 = n3 * 2;
            data.setKn3(HKn3);
            if (n3 >= 2.00) {
                lulbebkal = (float) 2.00;
            }
        }
        //Matkul 4
        data.setMatkul4(matkul4);
        if ("PENDIDIKAN AGAMA ISLAM".equals(matkul4)) {
            bebpai = (float) 3.00;
            data.setSandi4("DBPK1011");
            data.setSks4(3);
            data.setNm4(n4);
            HKn4 = n4 * 3;
            data.setKn4(HKn4);
            if (n4 >= 2.00) {
                lulbebpai = (float) 3.00;
            }
        } else if ("BAHASA INGGRIS II".equals(matkul4)) {
            bebbing = (float) 2.00;
            data.setSandi4("DBPK1092");
            data.setSks4(2);
            data.setNm4(n4);
            HKn4 = n4 * 2;
            data.setKn4(HKn4);
            if (n4 >= 2.00) {
                lulbebbing = (float) 2.00;
            }
        } else if ("ALGORITMA & PEMROGRAMAN II".equals(matkul4)) {
            bebap = (float) 3.00;
            data.setSandi4("DBKK1102");
            data.setSks4(3);
            data.setNm4(n4);
            HKn4 = n4 * 3;
            data.setKn4(HKn4);
            if (n4 >= 2.00) {
                lulbebap = bebap;
            }
        } else if ("STRUKTUR DATA".equals(matkul4)) {
            bebsd = (float) 3.00;
            data.setSandi4("DBKK1172");
            data.setSks4(3);
            data.setNm4(n4);
            HKn4 = n4 * 3;
            data.setKn4(HKn4);
            if (n4 >= 2.00) {
                lulbebsd = bebsd;
            }
        } else if ("MATEMATIKA DISKIT".equals(matkul4)) {
            bebmd = (float) 3.00;
            data.setSandi4("DBKK1191");
            data.setSks4(3);
            data.setNm4(n4);
            HKn4 = n4 * 3;
            data.setKn4(HKn4);
            if (n4 >= 2.00) {
                lulbebmd = bebmd;
            }
        } else if ("SISTEM OPERASI".equals(matkul4)) {
            bebso = (float) 3.00;
            data.setSandi4("DBKB1042");
            data.setSks4(3);
            data.setNm4(n4);
            HKn4 = n4 * 3;
            data.setKn4(HKn4);
            if (n4 >= 2.00) {
                lulbebso = bebso;
            }
        } else if ("PENGANTAR ARSITEKTUR KOMPUTER".equals(matkul4)) {
            bebpak = (float) 3.00;
            data.setSandi4("DBKK1272");
            data.setSks4(3);
            data.setNm4(n4);
            HKn4 = n4 * 3;
            data.setKn4(HKn4);
            if (n4 >= 2.00) {
                lulbebpak = bebpak;
            }
        } else if ("KALKULUS II".equals(matkul4)) {
            bebkal = (float) 2.00;
            data.setSandi4("DBKK1062");
            data.setSks4(2);
            data.setNm4(n4);
            HKn4 = n4 * 2;
            data.setKn4(HKn4);
            if (n4 >= 2.00) {
                lulbebkal = bebkal;
            }
        }
        //Matkul 5
        data.setMatkul5(matkul5);
        if ("PENDIDIKAN AGAMA ISLAM".equals(matkul5)) {
            bebpai = (float) 3.00;
            data.setSandi5("DBPK1011");
            data.setSks5(3);
            data.setNm5(n5);
            HKn5 = n5 * 3;
            data.setKn5(HKn5);
            if (n5 >= 2.00) {
                lulbebpai = bebpai;
            }
        } else if ("BAHASA INGGRIS II".equals(matkul5)) {
            bebbing = (float) 2.00;
            data.setSandi5("DBPK1092");
            data.setSks5(2);
            data.setNm5(n5);
            HKn5 = n5 * 2;
            data.setKn5(HKn5);
            if (n5 >= 2.00) {
                lulbebbing = bebbing;
            }
        } else if ("ALGORITMA & PEMROGRAMAN II".equals(matkul5)) {
            bebap = (float) 3.00;
            data.setSandi5("DBKK1102");
            data.setSks5(3);
            data.setNm5(n5);
            HKn5 = n5 * 3;
            data.setKn5(HKn5);
            if (n5 >= 2.00) {
                lulbebap = bebap;
            }
        } else if ("STRUKTUR DATA".equals(matkul5)) {
            bebsd = (float) 3.00;
            data.setSandi5("DBKK1172");
            data.setSks5(3);
            data.setNm5(n5);
            HKn5 = n5 * 3;
            data.setKn5(HKn5);
            if (n5 >= 2.00) {
                lulbebsd = bebsd;
            }
        } else if ("MATEMATIKA DISKIT".equals(matkul5)) {
            bebmd = (float) 3.00;
            data.setSandi5("DBKK1191");
            data.setSks5(3);
            data.setNm5(n5);
            HKn5 = n5 * 3;
            data.setKn5(HKn5);
            if (n5 >= 2.00) {
                lulbebmd = bebmd;
            }
        } else if ("SISTEM OPERASI".equals(matkul5)) {
            bebso = (float) 3.00;
            data.setSandi5("DBKB1042");
            data.setSks5(3);
            data.setNm5(n5);
            HKn5 = n5 * 3;
            data.setKn5(HKn5);
            if (n5 >= 2.00) {
                lulbebso = bebso;
            }
        } else if ("PENGANTAR ARSITEKTUR KOMPUTER".equals(matkul5)) {
            bebpak = (float) 3.00;
            data.setSandi5("DBKK1272");
            data.setSks5(3);
            data.setNm5(n5);
            HKn5 = n5 * 3;
            data.setKn5(HKn5);
            if (n5 >= 2.00) {
                lulbebpak = bebpak;
            }
        } else if ("KALKULUS II".equals(matkul5)) {
            bebkal = (float) 2.00;
            data.setSandi5("DBKK1062");
            data.setSks5(2);
            data.setNm5(n5);
            HKn5 = n5 * 2;
            data.setKn5(HKn5);
            if (n5 >= 2.00) {
                lulbebkal = bebkal;
            }
        }
        //Matkul 6
        data.setMatkul6(matkul6);
        if ("PENDIDIKAN AGAMA ISLAM".equals(matkul6)) {
            bebpai = (float) 3.00;
            data.setSandi6("DBPK1011");
            data.setSks6(3);
            data.setNm6(n6);
            HKn6 = n6 * 3;
            data.setKn6(HKn6);
            if (n6 >= 2.00) {
                lulbebpai = bebpai;
            }
        } else if ("BAHASA INGGRIS II".equals(matkul6)) {
            bebbing = (float) 3.00;
            data.setSandi6("DBPK1092");
            data.setSks6(2);
            data.setNm6(n6);
            HKn6 = n6 * 2;
            data.setKn6(HKn6);
            if (n6 >= 2.00) {
                lulbebbing = bebbing;
            }
        } else if ("ALGORITMA & PEMROGRAMAN II".equals(matkul6)) {
            bebap = (float) 3.00;
            data.setSandi6("DBKK1102");
            data.setSks6(3);
            data.setNm6(n6);
            HKn6 = n6 * 3;
            data.setKn6(HKn6);
            if (n6 >= 2.00) {
                lulbebap = bebap;
            }
        } else if ("STRUKTUR DATA".equals(matkul6)) {
            bebsd = (float) 3.00;
            data.setSandi6("DBKK1172");
            data.setSks6(3);
            data.setNm6(n6);
            HKn6 = n6 * 3;
            data.setKn6(HKn6);
            if (n6 >= 2.00) {
                lulbebsd = bebsd;
            }
        } else if ("MATEMATIKA DISKIT".equals(matkul6)) {
            bebmd = (float) 3.00;
            data.setSandi6("DBKK1191");
            data.setSks6(3);
            data.setNm6(n6);
            HKn6 = n6 * 3;
            data.setKn6(HKn6);
            if (n6 >= 2.00) {
                lulbebmd = bebmd;
            }
        } else if ("SISTEM OPERASI".equals(matkul6)) {
            bebso = (float) 3.00;
            data.setSandi6("DBKB1042");
            data.setSks6(3);
            data.setNm6(n6);
            HKn6 = n6 * 3;
            data.setKn6(HKn6);
            if (n6 >= 2.00) {
                lulbebso = bebso;
            }
        } else if ("PENGANTAR ARSITEKTUR KOMPUTER".equals(matkul6)) {
            bebpak = (float) 3.00;
            data.setSandi6("DBKK1272");
            data.setSks6(3);
            data.setNm6(n6);
            HKn6 = n6 * 3;
            data.setKn6(HKn6);
            if (n6 >= 2.00) {
                lulbebpak = bebpak;
            }
        } else if ("KALKULUS II".equals(matkul6)) {
            bebkal = (float) 2.00;
            data.setSandi6("DBKK1062");
            data.setSks6(2);
            data.setNm6(n6);
            HKn6 = n6 * 2;
            data.setKn6(HKn6);
            if (n6 >= 2.00) {
                lulbebkal = bebkal;
            }
        }
        //Matkul 7
        data.setMatkul7(matkul7);
        if ("PENDIDIKAN AGAMA ISLAM".equals(matkul7)) {
            bebpai = (float) 3.00;
            data.setSandi7("DBPK1011");
            data.setSks7(3);
            data.setNm7(n7);
            HKn7 = n7 * 3;
            data.setKn7(HKn7);
            if (n7 >= 2.00) {
                lulbebpai = bebpai;
            }
        } else if ("BAHASA INGGRIS II".equals(matkul7)) {
            bebbing = (float) 2.00;
            data.setSandi7("DBPK1092");
            data.setSks7(2);
            data.setNm7(n7);
            HKn7 = n7 * 2;
            data.setKn7(HKn7);
            if (n7 >= 2.00) {
                lulbebbing = bebbing;
            }
        } else if ("ALGORITMA & PEMROGRAMAN II".equals(matkul7)) {
            bebap = (float) 3.00;
            data.setSandi7("DBKK1102");
            data.setSks7(3);
            data.setNm7(n7);
            HKn7 = n7 * 3;
            data.setKn7(HKn7);
            if (n7 >= 2.00) {
                lulbebap = bebap;
            }
        } else if ("STRUKTUR DATA".equals(matkul7)) {
            bebsd = (float) 3.00;
            data.setSandi7("DBKK1172");
            data.setSks7(3);
            data.setNm7(n7);
            HKn7 = n7 * 3;
            data.setKn7(HKn7);
            if (n7 >= 2.00) {
                lulbebsd = bebsd;
            }
        } else if ("MATEMATIKA DISKIT".equals(matkul7)) {
            bebmd = (float) 3.00;
            data.setSandi7("DBKK1191");
            data.setSks7(3);
            data.setNm7(n7);
            HKn7 = n7 * 3;
            data.setKn7(HKn7);
            if (n7 >= 2.00) {
                lulbebmd = bebmd;
            }
        } else if ("SISTEM OPERASI".equals(matkul7)) {
            bebso = (float) 3.00;
            data.setSandi7("DBKB1042");
            data.setSks7(3);
            data.setNm7(n7);
            HKn7 = n7 * 3;
            data.setKn7(HKn7);
            if (n7 >= 2.00) {
                lulbebso = bebso;
            }
        } else if ("PENGANTAR ARSITEKTUR KOMPUTER".equals(matkul7)) {
            bebpak = (float) 3.00;
            data.setSandi7("DBKK1272");
            data.setSks7(3);
            data.setNm7(n7);
            HKn7 = n7 * 3;
            data.setKn7(HKn7);
            if (n7 >= 2.00) {
                lulbebpak = bebpak;
            }
        } else if ("KALKULUS II".equals(matkul7)) {
            bebkal = (float) 2.00;
            data.setSandi7("DBKK1062");
            data.setSks7(2);
            data.setNm7(n7);
            HKn7 = n7 * 2;
            data.setKn7(HKn7);
            if (n7 >= 2.00) {
                lulbebkal = bebkal;
            }
        }
        //Matkul 8
        data.setMatkul8(matkul8);
        if ("PENDIDIKAN AGAMA ISLAM".equals(matkul8)) {
            bebpai = (float) 3.00;
            data.setSandi8("DBPK1011");
            data.setSks8(3);
            data.setNm8(n8);
            HKn8 = n8 * 3;
            data.setKn8(HKn8);
            if (n8 >= 2.00) {
                lulbebpai = bebpai;
            }
        } else if ("BAHASA INGGRIS II".equals(matkul8)) {
            bebbing = (float) 2.00;
            data.setSandi8("DBPK1092");
            data.setSks8(2);
            data.setNm8(n8);
            HKn8 = n8 * 2;
            data.setKn8(HKn8);
            if (n8 >= 2.00) {
                lulbebbing = bebbing;
            }
        } else if ("ALGORITMA & PEMROGRAMAN II".equals(matkul8)) {
            bebap = (float) 3.00;
            data.setSandi8("DBKK1102");
            data.setSks8(3);
            data.setNm8(n8);
            HKn8 = n8 * 3;
            data.setKn8(HKn8);
            if (n8 >= 2.00) {
                lulbebap = bebap;
            }
        } else if ("STRUKTUR DATA".equals(matkul8)) {
            bebsd = (float) 3.00;
            data.setSandi8("DBKK1172");
            data.setSks8(3);
            data.setNm8(n8);
            HKn8 = n8 * 3;
            data.setKn8(HKn8);
            if (n8 >= 2.00) {
                lulbebsd = bebsd;
            }
        } else if ("MATEMATIKA DISKIT".equals(matkul8)) {
            bebmd = (float) 3.00;
            data.setSandi8("DBKK1191");
            data.setSks8(3);
            data.setNm8(n8);
            HKn8 = n8 * 3;
            data.setKn8(HKn8);
            if (n8 >= 2.00) {
                lulbebmd = bebmd;
            }
        } else if ("SISTEM OPERASI".equals(matkul8)) {
            bebso = (float) 3.00;
            data.setSandi8("DBKB1042");
            data.setSks8(3);
            data.setNm8(n8);
            HKn8 = n8 * 3;
            data.setKn8(HKn8);
            if (n8 >= 2.00) {
                lulbebso = bebso;
            }
        } else if ("PENGANTAR ARSITEKTUR KOMPUTER".equals(matkul8)) {
            bebpak = (float) 3.00;
            data.setSandi8("DBKK1272");
            data.setSks8(3);
            data.setNm8(n8);
            HKn8 = n8 * 3;
            data.setKn8(HKn8);
            if (n8 >= 2.00) {
                lulbebpak = bebpak;
            }
        } else if ("KALKULUS II".equals(matkul8)) {
            bebkal = (float) 2.00;
            data.setSandi8("DBKK1062");
            data.setSks8(2);
            data.setNm8(n8);
            HKn8 = n8 * 2;
            data.setKn8(HKn8);
            if (n8 >= 2.00) {
                lulbebkal = bebkal;
            }
        }
        data.setNo1("1");
        data.setNo2("2");
        data.setNo3("3");
        data.setNo4("4");
        data.setNo5("5");
        data.setNo6("6");
        data.setNo7("7");
        data.setNo8("8");
        listOfDummyData.add(data);
        JRBeanCollectionDataSource dataSource = new JRBeanCollectionDataSource(listOfDummyData);
        System.out.println(dataSource.getRecordCount());
        params.put("dosenp", "(" + padosen + ")");
        params.put("nama", nama);
        params.put("nim", nim);
        params.put("semester", semester);
        String j = (String) pa.getSelectedItem();
        if (j.equals("PUTU BAGUS ADIDYANA A.P., ST., M.Kom.")) {
            params.put("nodosenp", "198910222 ----");
        }
        if (j.equals("NOVA NOOR KAMALA SARI, ST., M.Kom.")) {
            params.put("nodosenp", "198904072 ----");
        }
        params.put("jurusan", "DBC1 TEK.INFORMATIKA S1");
        totalbeb = bebpai + bebbing + bebap + bebsd + bebmd + bebso + bebpak + bebkal;
        totallulus = lulbebpai + lulbebbing + lulbebap + lulbebsd + lulbebmd + lulbebso + lulbebpak + lulbebkal;
        totmutusem = HKn1 + HKn2 + HKn3 + HKn4 + HKn5 + HKn6 + HKn7 + HKn8;
        ipsemtot = totmutusem / totalbeb;
        mutusemlalu = semlalu * 24;
        mutukumul = mutusemlalu + totmutusem;
        ipkumul = (ipsemtot + semlalu) / 2;
        bebankumul = 24 + totalbeb;
        luluskumul = 24 + totallulus;
        params.put("bebansks", totalbeb);
        params.put("lulussks", totallulus);
        params.put("semangkamutu", totmutusem);
        params.put("ipsem", ipsemtot);
        params.put("kumangkamutu", mutukumul);
        params.put("ipkum", ipkumul);
        params.put("bebankum", bebankumul);
        params.put("luluskum", luluskumul);
        params.put("sksyad", sksyad);
        params.put("dataSource", dataSource);
        //net.sf.jasperreports.engine.JRDataSource
        try {
            JasperPrint printer = JasperFillManager.fillReport(getClass().getResourceAsStream("isi.jasper"), params, new JREmptyDataSource());
            JasperViewer jv = new JasperViewer(printer);
            jv.show();
        } catch (JRException ex) {
            ex.printStackTrace();
        }
    }//GEN-LAST:event_submitActionPerformed

    private void paActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_paActionPerformed

    private void cmbmatkul1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmatkul1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmatkul1ActionPerformed

    private void cmbmatkul2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmatkul2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmatkul2ActionPerformed

    private void cmbmatkul3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmatkul3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmatkul3ActionPerformed

    private void cmbmatkul4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmatkul4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmatkul4ActionPerformed

    private void cmbmatkul5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmatkul5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmatkul5ActionPerformed

    private void cmbmatkul6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmatkul6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmatkul6ActionPerformed

    private void cmbmatkul7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmatkul7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmatkul7ActionPerformed

    private void cmbmatkul8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbmatkul8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbmatkul8ActionPerformed

    private void inipsemlaluActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inipsemlaluActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inipsemlaluActionPerformed
    float ParseFloat(String strNumber) {
        if (strNumber != null && strNumber.length() > 0) {
            try {
                return Float.parseFloat(strNumber);
            } catch (Exception e) {
                return -1;   // or some value to mark this field is wrong. or make a function validates field first ...
            }
        } else {
            return 0;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InputDataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InputDataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InputDataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InputDataDiri.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InputDataDiri().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmbmatkul1;
    private javax.swing.JComboBox<String> cmbmatkul2;
    private javax.swing.JComboBox<String> cmbmatkul3;
    private javax.swing.JComboBox<String> cmbmatkul4;
    private javax.swing.JComboBox<String> cmbmatkul5;
    private javax.swing.JComboBox<String> cmbmatkul6;
    private javax.swing.JComboBox<String> cmbmatkul7;
    private javax.swing.JComboBox<String> cmbmatkul8;
    public javax.swing.JTextField inipsemlalu;
    public javax.swing.JTextField innama;
    public javax.swing.JTextField innim;
    public javax.swing.JTextField insemester;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nilai1;
    private javax.swing.JTextField nilai2;
    private javax.swing.JTextField nilai3;
    private javax.swing.JTextField nilai4;
    private javax.swing.JTextField nilai5;
    private javax.swing.JTextField nilai6;
    private javax.swing.JTextField nilai7;
    private javax.swing.JTextField nilai8;
    public javax.swing.JComboBox<String> pa;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
